export const dummyPlayers = [
  {
    player: {
      id: 642,
      name: 'S. Agüero',
      firstname: 'Sergio Leonel',
      lastname: 'Agüero del Castillo',
      age: 33,
      birth: {
        date: '1988-06-02',
        place: 'Quilmes',
        country: 'Argentina',
      },
      nationality: 'Argentina',
      height: '173 cm',
      weight: '70 kg',
      injured: false,
      photo: 'https://media-1.api-sports.io/football/players/642.png',
    },
    statistics: [
      {
        team: {
          id: 50,
          name: 'Manchester City',
          logo: 'https://media-1.api-sports.io/football/teams/50.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-3.api-sports.io/football/leagues/39.png',
          flag: 'https://media-3.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 12,
          lineups: 7,
          minutes: 559,
          number: null,
          position: 'Attacker',
          rating: '6.900000',
          captain: false,
        },
        substitutes: {
          in: 5,
          out: 5,
          bench: 12,
        },
        shots: {
          total: 17,
          on: 12,
        },
        goals: {
          total: 4,
          conceded: 0,
          assists: 1,
          saves: null,
        },
        passes: {
          total: 171,
          key: 7,
          accuracy: 13,
        },
        tackles: {
          total: 4,
          blocks: null,
          interceptions: 2,
        },
        duels: {
          total: 51,
          won: 21,
        },
        dribbles: {
          attempts: 13,
          success: 8,
          past: null,
        },
        fouls: {
          drawn: 7,
          committed: 2,
        },
        cards: {
          yellow: 0,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: 1,
          missed: 1,
          saved: null,
        },
      },
    ],
  },
  {
    player: {
      id: 883,
      name: 'Lee Grant',
      firstname: 'Lee',
      lastname: 'Grant',
      age: 39,
      birth: {
        date: '1983-01-27',
        place: 'Hemel Hempstead',
        country: 'England',
      },
      nationality: 'England',
      height: '193 cm',
      weight: '83 kg',
      injured: false,
      photo: 'https://media-1.api-sports.io/football/players/883.png',
    },
    statistics: [
      {
        team: {
          id: 33,
          name: 'Manchester United',
          logo: 'https://media-2.api-sports.io/football/teams/33.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-3.api-sports.io/football/leagues/39.png',
          flag: 'https://media-1.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 0,
          lineups: 0,
          minutes: 0,
          number: null,
          position: 'Goalkeeper',
          rating: null,
          captain: false,
        },
        substitutes: {
          in: 0,
          out: 0,
          bench: 6,
        },
        shots: {
          total: null,
          on: null,
        },
        goals: {
          total: 0,
          conceded: 0,
          assists: null,
          saves: null,
        },
        passes: {
          total: null,
          key: null,
          accuracy: null,
        },
        tackles: {
          total: null,
          blocks: null,
          interceptions: null,
        },
        duels: {
          total: null,
          won: null,
        },
        dribbles: {
          attempts: null,
          success: null,
          past: null,
        },
        fouls: {
          drawn: null,
          committed: null,
        },
        cards: {
          yellow: 0,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: 0,
        },
      },
    ],
  },
  {
    player: {
      id: 1200,
      name: 'B. Ivanović',
      firstname: 'Branislav',
      lastname: 'Ivanović',
      age: 37,
      birth: {
        date: '1984-02-22',
        place: 'Sremska Mitrovica',
        country: 'Serbia',
      },
      nationality: 'Serbia',
      height: '185 cm',
      weight: '89 kg',
      injured: false,
      photo: 'https://media-3.api-sports.io/football/players/1200.png',
    },
    statistics: [
      {
        team: {
          id: 60,
          name: 'West Brom',
          logo: 'https://media-2.api-sports.io/football/teams/60.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-2.api-sports.io/football/leagues/39.png',
          flag: 'https://media-1.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 13,
          lineups: 8,
          minutes: 765,
          number: null,
          position: 'Defender',
          rating: '6.566666',
          captain: false,
        },
        substitutes: {
          in: 5,
          out: 3,
          bench: 12,
        },
        shots: {
          total: 3,
          on: 1,
        },
        goals: {
          total: 0,
          conceded: 0,
          assists: null,
          saves: null,
        },
        passes: {
          total: 317,
          key: 1,
          accuracy: 26,
        },
        tackles: {
          total: 14,
          blocks: 5,
          interceptions: 8,
        },
        duels: {
          total: 58,
          won: 31,
        },
        dribbles: {
          attempts: null,
          success: null,
          past: null,
        },
        fouls: {
          drawn: 4,
          committed: 11,
        },
        cards: {
          yellow: 2,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
    ],
  },
  {
    player: {
      id: 2281,
      name: 'Gary Cahill',
      firstname: 'Gary',
      lastname: 'Cahill',
      age: 37,
      birth: {
        date: '1985-12-19',
        place: 'Dronfield',
        country: 'England',
      },
      nationality: 'England',
      height: '193 cm',
      weight: '86 kg',
      injured: false,
      photo: 'https://media-2.api-sports.io/football/players/2281.png',
    },
    statistics: [
      {
        team: {
          id: 52,
          name: 'Crystal Palace',
          logo: 'https://media-3.api-sports.io/football/teams/52.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-3.api-sports.io/football/leagues/39.png',
          flag: 'https://media-3.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 20,
          lineups: 20,
          minutes: 1800,
          number: null,
          position: 'Defender',
          rating: '6.765000',
          captain: false,
        },
        substitutes: {
          in: 0,
          out: 0,
          bench: 7,
        },
        shots: {
          total: 8,
          on: 3,
        },
        goals: {
          total: 1,
          conceded: 0,
          assists: 1,
          saves: null,
        },
        passes: {
          total: 746,
          key: 8,
          accuracy: 30,
        },
        tackles: {
          total: 13,
          blocks: 22,
          interceptions: 13,
        },
        duels: {
          total: 139,
          won: 86,
        },
        dribbles: {
          attempts: 1,
          success: 1,
          past: null,
        },
        fouls: {
          drawn: 3,
          committed: 12,
        },
        cards: {
          yellow: 3,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
    ],
  },
  {
    player: {
      id: 2795,
      name: 'G. Sigurðsson',
      firstname: 'Gylfi Þór',
      lastname: 'Sigurðsson',
      age: 33,
      birth: {
        date: '1989-09-08',
        place: 'Reykjavík',
        country: 'Iceland',
      },
      nationality: 'Iceland',
      height: '186 cm',
      weight: '79 kg',
      injured: false,
      photo: 'https://media-3.api-sports.io/football/players/2795.png',
    },
    statistics: [
      {
        team: {
          id: 45,
          name: 'Everton',
          logo: 'https://media-3.api-sports.io/football/teams/45.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-1.api-sports.io/football/leagues/39.png',
          flag: 'https://media-3.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 36,
          lineups: 24,
          minutes: 2255,
          number: null,
          position: 'Midfielder',
          rating: '6.908333',
          captain: false,
        },
        substitutes: {
          in: 12,
          out: 12,
          bench: 14,
        },
        shots: {
          total: 33,
          on: 17,
        },
        goals: {
          total: 6,
          conceded: 0,
          assists: 5,
          saves: null,
        },
        passes: {
          total: 853,
          key: 44,
          accuracy: 20,
        },
        tackles: {
          total: 30,
          blocks: 2,
          interceptions: 34,
        },
        duels: {
          total: 169,
          won: 67,
        },
        dribbles: {
          attempts: 26,
          success: 14,
          past: null,
        },
        fouls: {
          drawn: 18,
          committed: 22,
        },
        cards: {
          yellow: 2,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: 3,
          missed: 1,
          saved: null,
        },
      },
    ],
  },
  {
    player: {
      id: 18774,
      name: 'W. Morgan',
      firstname: 'Wes',
      lastname: 'Morgan',
      age: 37,
      birth: {
        date: '1984-01-21',
        place: 'Nottingham',
        country: 'England',
      },
      nationality: 'Jamaica',
      height: '186 cm',
      weight: '101 kg',
      injured: false,
      photo: 'https://media-1.api-sports.io/football/players/18774.png',
    },
    statistics: [
      {
        team: {
          id: 46,
          name: 'Leicester',
          logo: 'https://media-3.api-sports.io/football/teams/46.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-1.api-sports.io/football/leagues/39.png',
          flag: 'https://media-3.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 3,
          lineups: 0,
          minutes: 15,
          number: null,
          position: 'Defender',
          rating: '6.450000',
          captain: false,
        },
        substitutes: {
          in: 3,
          out: 0,
          bench: 13,
        },
        shots: {
          total: null,
          on: null,
        },
        goals: {
          total: 0,
          conceded: 0,
          assists: null,
          saves: null,
        },
        passes: {
          total: 5,
          key: null,
          accuracy: 2,
        },
        tackles: {
          total: null,
          blocks: null,
          interceptions: null,
        },
        duels: {
          total: null,
          won: null,
        },
        dribbles: {
          attempts: null,
          success: null,
          past: null,
        },
        fouls: {
          drawn: null,
          committed: null,
        },
        cards: {
          yellow: 0,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
    ],
  },
  {
    player: {
      id: 18826,
      name: 'Mark Noble',
      firstname: 'Mark',
      lastname: 'Noble',
      age: 35,
      birth: {
        date: '1987-05-08',
        place: 'Canning Town',
        country: 'England',
      },
      nationality: 'England',
      height: '180 cm',
      weight: '70 kg',
      injured: false,
      photo: 'https://media-2.api-sports.io/football/players/18826.png',
    },
    statistics: [
      {
        team: {
          id: 48,
          name: 'West Ham',
          logo: 'https://media-3.api-sports.io/football/teams/48.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-3.api-sports.io/football/leagues/39.png',
          flag: 'https://media-1.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 21,
          lineups: 8,
          minutes: 705,
          number: null,
          position: 'Midfielder',
          rating: '6.594117',
          captain: false,
        },
        substitutes: {
          in: 13,
          out: 6,
          bench: 24,
        },
        shots: {
          total: 1,
          on: null,
        },
        goals: {
          total: 0,
          conceded: 0,
          assists: null,
          saves: null,
        },
        passes: {
          total: 430,
          key: 5,
          accuracy: 20,
        },
        tackles: {
          total: 8,
          blocks: 3,
          interceptions: 13,
        },
        duels: {
          total: 48,
          won: 21,
        },
        dribbles: {
          attempts: 2,
          success: 2,
          past: null,
        },
        fouls: {
          drawn: 8,
          committed: 9,
        },
        cards: {
          yellow: 1,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
    ],
  },
  {
    player: {
      id: 18829,
      name: 'Jack Wilshere',
      firstname: 'Jack',
      lastname: 'Wilshere',
      age: 30,
      birth: {
        date: '1992-01-01',
        place: 'Stevenage',
        country: 'England',
      },
      nationality: 'England',
      height: '172 cm',
      weight: '68 kg',
      injured: false,
      photo: 'https://media-1.api-sports.io/football/players/18829.png',
    },
    statistics: [
      {
        team: {
          id: 48,
          name: 'West Ham',
          logo: 'https://media-1.api-sports.io/football/teams/48.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-1.api-sports.io/football/leagues/39.png',
          flag: 'https://media-1.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 0,
          lineups: 0,
          minutes: 0,
          number: null,
          position: 'Midfielder',
          rating: null,
          captain: false,
        },
        substitutes: {
          in: 0,
          out: 0,
          bench: 0,
        },
        shots: {
          total: null,
          on: null,
        },
        goals: {
          total: 0,
          conceded: null,
          assists: null,
          saves: null,
        },
        passes: {
          total: null,
          key: null,
          accuracy: null,
        },
        tackles: {
          total: null,
          blocks: null,
          interceptions: null,
        },
        duels: {
          total: null,
          won: null,
        },
        dribbles: {
          attempts: null,
          success: null,
          past: null,
        },
        fouls: {
          drawn: null,
          committed: null,
        },
        cards: {
          yellow: 0,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: null,
          missed: null,
          saved: null,
        },
      },
    ],
  },
  {
    player: {
      id: 18975,
      name: 'D. Pröpper',
      firstname: 'David Petrus Wenceslaus Henri',
      lastname: 'Pröpper',
      age: 31,
      birth: {
        date: '1991-09-02',
        place: 'Arnhem',
        country: 'Netherlands',
      },
      nationality: 'Netherlands',
      height: '185 cm',
      weight: '79 kg',
      injured: false,
      photo: 'https://media-1.api-sports.io/football/players/18975.png',
    },
    statistics: [
      {
        team: {
          id: 51,
          name: 'Brighton',
          logo: 'https://media-2.api-sports.io/football/teams/51.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-2.api-sports.io/football/leagues/39.png',
          flag: 'https://media-3.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 7,
          lineups: 2,
          minutes: 210,
          number: null,
          position: 'Midfielder',
          rating: '6.500000',
          captain: false,
        },
        substitutes: {
          in: 5,
          out: 2,
          bench: 19,
        },
        shots: {
          total: 2,
          on: 2,
        },
        goals: {
          total: 0,
          conceded: 0,
          assists: null,
          saves: null,
        },
        passes: {
          total: 93,
          key: null,
          accuracy: 10,
        },
        tackles: {
          total: 6,
          blocks: null,
          interceptions: 1,
        },
        duels: {
          total: 25,
          won: 11,
        },
        dribbles: {
          attempts: 3,
          success: 2,
          past: null,
        },
        fouls: {
          drawn: null,
          committed: 1,
        },
        cards: {
          yellow: 0,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
    ],
  },
  {
    player: {
      id: 18980,
      name: 'J. Izquierdo',
      firstname: 'José Heriberto',
      lastname: 'Izquierdo Mena',
      age: 30,
      birth: {
        date: '1992-07-07',
        place: 'Pereira',
        country: 'Colombia',
      },
      nationality: 'Colombia',
      height: '171 cm',
      weight: '73 kg',
      injured: false,
      photo: 'https://media-3.api-sports.io/football/players/18980.png',
    },
    statistics: [
      {
        team: {
          id: 51,
          name: 'Brighton',
          logo: 'https://media-3.api-sports.io/football/teams/51.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-3.api-sports.io/football/leagues/39.png',
          flag: 'https://media-1.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 1,
          lineups: 0,
          minutes: 8,
          number: null,
          position: 'Attacker',
          rating: '6.700000',
          captain: false,
        },
        substitutes: {
          in: 1,
          out: 0,
          bench: 10,
        },
        shots: {
          total: 1,
          on: 1,
        },
        goals: {
          total: 0,
          conceded: 0,
          assists: null,
          saves: null,
        },
        passes: {
          total: 7,
          key: null,
          accuracy: 6,
        },
        tackles: {
          total: null,
          blocks: null,
          interceptions: null,
        },
        duels: {
          total: 1,
          won: null,
        },
        dribbles: {
          attempts: 1,
          success: null,
          past: null,
        },
        fouls: {
          drawn: null,
          committed: null,
        },
        cards: {
          yellow: 0,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
    ],
  },
  {
    player: {
      id: 19153,
      name: 'G. Barry',
      firstname: 'Gareth',
      lastname: 'Barry',
      age: 39,
      birth: {
        date: '1981-02-23',
        place: 'Hastings',
        country: 'England',
      },
      nationality: 'England',
      height: '183 cm',
      weight: '78 kg',
      injured: false,
      photo: 'https://media-1.api-sports.io/football/players/19153.png',
    },
    statistics: [
      {
        team: {
          id: 60,
          name: 'West Brom',
          logo: 'https://media-2.api-sports.io/football/teams/60.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-3.api-sports.io/football/leagues/39.png',
          flag: 'https://media-1.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: null,
          lineups: null,
          minutes: null,
          number: null,
          position: 'Midfielder',
          rating: null,
          captain: false,
        },
        substitutes: {
          in: null,
          out: null,
          bench: null,
        },
        shots: {
          total: null,
          on: null,
        },
        goals: {
          total: null,
          conceded: null,
          assists: null,
          saves: null,
        },
        passes: {
          total: null,
          key: null,
          accuracy: null,
        },
        tackles: {
          total: null,
          blocks: null,
          interceptions: null,
        },
        duels: {
          total: null,
          won: null,
        },
        dribbles: {
          attempts: null,
          success: null,
          past: null,
        },
        fouls: {
          drawn: null,
          committed: null,
        },
        cards: {
          yellow: null,
          yellowred: null,
          red: null,
        },
        penalty: {
          won: null,
          commited: null,
          scored: null,
          missed: null,
          saved: null,
        },
      },
    ],
  },
  {
    player: {
      id: 19186,
      name: 'Ahmed El Mohamady',
      firstname: 'Ahmed Eissa',
      lastname: 'El Mohamady Abdel Fattah',
      age: 34,
      birth: {
        date: '1987-09-09',
        place: 'Basyoun',
        country: 'Egypt',
      },
      nationality: 'Egypt',
      height: '183 cm',
      weight: '75 kg',
      injured: false,
      photo: 'https://media-1.api-sports.io/football/players/19186.png',
    },
    statistics: [
      {
        team: {
          id: 66,
          name: 'Aston Villa',
          logo: 'https://media-3.api-sports.io/football/teams/66.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-3.api-sports.io/football/leagues/39.png',
          flag: 'https://media-3.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 14,
          lineups: 8,
          minutes: 833,
          number: null,
          position: 'Defender',
          rating: '6.900000',
          captain: false,
        },
        substitutes: {
          in: 6,
          out: 0,
          bench: 30,
        },
        shots: {
          total: 8,
          on: 1,
        },
        goals: {
          total: 0,
          conceded: 0,
          assists: null,
          saves: null,
        },
        passes: {
          total: 470,
          key: 13,
          accuracy: 26,
        },
        tackles: {
          total: 17,
          blocks: 3,
          interceptions: 17,
        },
        duels: {
          total: 64,
          won: 40,
        },
        dribbles: {
          attempts: 3,
          success: 2,
          past: null,
        },
        fouls: {
          drawn: 3,
          committed: 6,
        },
        cards: {
          yellow: 2,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
    ],
  },
  {
    player: {
      id: 19373,
      name: 'Michael Hector',
      firstname: 'Michael',
      lastname: 'Hector',
      age: 30,
      birth: {
        date: '1992-07-19',
        place: 'London',
        country: 'England',
      },
      nationality: 'Jamaica',
      height: '193 cm',
      weight: '82 kg',
      injured: false,
      photo: 'https://media-1.api-sports.io/football/players/19373.png',
    },
    statistics: [
      {
        team: {
          id: 36,
          name: 'Fulham',
          logo: 'https://media-2.api-sports.io/football/teams/36.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-1.api-sports.io/football/leagues/39.png',
          flag: 'https://media-2.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 4,
          lineups: 3,
          minutes: 264,
          number: null,
          position: 'Defender',
          rating: '6.450000',
          captain: false,
        },
        substitutes: {
          in: 1,
          out: 1,
          bench: 24,
        },
        shots: {
          total: null,
          on: null,
        },
        goals: {
          total: 0,
          conceded: 0,
          assists: null,
          saves: null,
        },
        passes: {
          total: 186,
          key: 1,
          accuracy: 36,
        },
        tackles: {
          total: 3,
          blocks: 2,
          interceptions: null,
        },
        duels: {
          total: 29,
          won: 15,
        },
        dribbles: {
          attempts: 3,
          success: 3,
          past: null,
        },
        fouls: {
          drawn: 3,
          committed: 5,
        },
        cards: {
          yellow: 2,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
    ],
  },
  {
    player: {
      id: 19533,
      name: 'Jota Peleteiro',
      firstname: 'José Ignacio',
      lastname: 'Peleteiro Ramallo',
      age: 30,
      birth: {
        date: '1991-06-16',
        place: 'Vigo',
        country: 'Spain',
      },
      nationality: 'Spain',
      height: '180 cm',
      weight: '70 kg',
      injured: false,
      photo: 'https://media-3.api-sports.io/football/players/19533.png',
    },
    statistics: [
      {
        team: {
          id: 66,
          name: 'Aston Villa',
          logo: 'https://media-3.api-sports.io/football/teams/66.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-2.api-sports.io/football/leagues/39.png',
          flag: 'https://media-1.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 0,
          lineups: 0,
          minutes: 0,
          number: null,
          position: 'Midfielder',
          rating: null,
          captain: false,
        },
        substitutes: {
          in: 0,
          out: 0,
          bench: 0,
        },
        shots: {
          total: null,
          on: null,
        },
        goals: {
          total: 0,
          conceded: null,
          assists: null,
          saves: null,
        },
        passes: {
          total: null,
          key: null,
          accuracy: null,
        },
        tackles: {
          total: null,
          blocks: null,
          interceptions: null,
        },
        duels: {
          total: null,
          won: null,
        },
        dribbles: {
          attempts: null,
          success: null,
          past: null,
        },
        fouls: {
          drawn: null,
          committed: null,
        },
        cards: {
          yellow: 0,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: null,
          missed: null,
          saved: null,
        },
      },
    ],
  },
  {
    player: {
      id: 82227,
      name: 'Stephen Francis Henderson',
      firstname: 'Stephen Francis',
      lastname: 'Henderson',
      age: 34,
      birth: {
        date: '1988-05-02',
        place: 'Dublin',
        country: 'Republic of Ireland',
      },
      nationality: 'Republic of Ireland',
      height: '193 cm',
      weight: '87 kg',
      injured: false,
      photo: 'https://media-2.api-sports.io/football/players/82227.png',
    },
    statistics: [
      {
        team: {
          id: 52,
          name: 'Crystal Palace',
          logo: 'https://media-1.api-sports.io/football/teams/52.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-3.api-sports.io/football/leagues/39.png',
          flag: 'https://media-2.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 0,
          lineups: 0,
          minutes: 0,
          number: null,
          position: 'Goalkeeper',
          rating: null,
          captain: false,
        },
        substitutes: {
          in: 0,
          out: 0,
          bench: 3,
        },
        shots: {
          total: null,
          on: null,
        },
        goals: {
          total: 0,
          conceded: 0,
          assists: null,
          saves: null,
        },
        passes: {
          total: null,
          key: null,
          accuracy: null,
        },
        tackles: {
          total: null,
          blocks: null,
          interceptions: null,
        },
        duels: {
          total: null,
          won: null,
        },
        dribbles: {
          attempts: null,
          success: null,
          past: null,
        },
        fouls: {
          drawn: null,
          committed: null,
        },
        cards: {
          yellow: 0,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: 0,
        },
      },
    ],
  },
  {
    player: {
      id: 138936,
      name: 'K. Hayden',
      firstname: 'Kaine',
      lastname: 'Kesler Hayden',
      age: 18,
      birth: {
        date: '2003-05-25',
        place: null,
        country: 'England',
      },
      nationality: 'England',
      height: null,
      weight: null,
      injured: false,
      photo: 'https://media-2.api-sports.io/football/players/138936.png',
    },
    statistics: [
      {
        team: {
          id: 66,
          name: 'Aston Villa',
          logo: 'https://media-2.api-sports.io/football/teams/66.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-3.api-sports.io/football/leagues/39.png',
          flag: 'https://media-1.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 0,
          lineups: 0,
          minutes: 0,
          number: null,
          position: 'Midfielder',
          rating: null,
          captain: false,
        },
        substitutes: {
          in: 0,
          out: 0,
          bench: 2,
        },
        shots: {
          total: null,
          on: null,
        },
        goals: {
          total: 0,
          conceded: 0,
          assists: null,
          saves: null,
        },
        passes: {
          total: null,
          key: null,
          accuracy: null,
        },
        tackles: {
          total: null,
          blocks: null,
          interceptions: null,
        },
        duels: {
          total: null,
          won: null,
        },
        dribbles: {
          attempts: null,
          success: null,
          past: null,
        },
        fouls: {
          drawn: null,
          committed: null,
        },
        cards: {
          yellow: 0,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
    ],
  },
  {
    player: {
      id: 162517,
      name: 'L. Dendoncker',
      firstname: 'Lars',
      lastname: 'Dendoncker',
      age: 21,
      birth: {
        date: '2001-04-03',
        place: null,
        country: 'Belgium',
      },
      nationality: 'Belgium',
      height: '188 cm',
      weight: null,
      injured: false,
      photo: 'https://media-3.api-sports.io/football/players/162517.png',
    },
    statistics: [
      {
        team: {
          id: 51,
          name: 'Brighton',
          logo: 'https://media-1.api-sports.io/football/teams/51.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-3.api-sports.io/football/leagues/39.png',
          flag: 'https://media-2.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 0,
          lineups: 0,
          minutes: 0,
          number: null,
          position: 'Defender',
          rating: null,
          captain: false,
        },
        substitutes: {
          in: 0,
          out: 0,
          bench: 0,
        },
        shots: {
          total: null,
          on: null,
        },
        goals: {
          total: 0,
          conceded: null,
          assists: null,
          saves: null,
        },
        passes: {
          total: null,
          key: null,
          accuracy: null,
        },
        tackles: {
          total: null,
          blocks: null,
          interceptions: null,
        },
        duels: {
          total: null,
          won: null,
        },
        dribbles: {
          attempts: null,
          success: null,
          past: null,
        },
        fouls: {
          drawn: null,
          committed: null,
        },
        cards: {
          yellow: 0,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: null,
          missed: null,
          saved: null,
        },
      },
    ],
  },
  {
    player: {
      id: 192348,
      name: 'Jamie Soule',
      firstname: 'Jamie',
      lastname: 'Soule',
      age: 22,
      birth: {
        date: '2000-11-26',
        place: 'Cheltenham',
        country: 'England',
      },
      nationality: 'England',
      height: '183 cm',
      weight: '75 kg',
      injured: false,
      photo: 'https://media-2.api-sports.io/football/players/192348.png',
    },
    statistics: [
      {
        team: {
          id: 60,
          name: 'West Brom',
          logo: 'https://media-1.api-sports.io/football/teams/60.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-3.api-sports.io/football/leagues/39.png',
          flag: 'https://media-3.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 0,
          lineups: 0,
          minutes: 0,
          number: null,
          position: 'Attacker',
          rating: null,
          captain: false,
        },
        substitutes: {
          in: 0,
          out: 0,
          bench: 0,
        },
        shots: {
          total: null,
          on: null,
        },
        goals: {
          total: 0,
          conceded: null,
          assists: null,
          saves: null,
        },
        passes: {
          total: null,
          key: null,
          accuracy: null,
        },
        tackles: {
          total: null,
          blocks: null,
          interceptions: null,
        },
        duels: {
          total: null,
          won: null,
        },
        dribbles: {
          attempts: null,
          success: null,
          past: null,
        },
        fouls: {
          drawn: null,
          committed: null,
        },
        cards: {
          yellow: 0,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: null,
          missed: null,
          saved: null,
        },
      },
    ],
  },
  {
    player: {
      id: 199312,
      name: 'Brandon Leroy Pierrick Keutcha',
      firstname: 'Brandon Leroy',
      lastname: 'Pierrick Keutcha',
      age: 21,
      birth: {
        date: '2001-12-10',
        place: 'London',
        country: 'England',
      },
      nationality: 'England',
      height: '182 cm',
      weight: '79 kg',
      injured: false,
      photo: 'https://media-2.api-sports.io/football/players/199312.png',
    },
    statistics: [
      {
        team: {
          id: 52,
          name: 'Crystal Palace',
          logo: 'https://media-1.api-sports.io/football/teams/52.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-1.api-sports.io/football/leagues/39.png',
          flag: 'https://media-1.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 0,
          lineups: 0,
          minutes: 0,
          number: null,
          position: 'Attacker',
          rating: null,
          captain: false,
        },
        substitutes: {
          in: 0,
          out: 0,
          bench: 0,
        },
        shots: {
          total: null,
          on: null,
        },
        goals: {
          total: 0,
          conceded: null,
          assists: null,
          saves: null,
        },
        passes: {
          total: null,
          key: null,
          accuracy: null,
        },
        tackles: {
          total: null,
          blocks: null,
          interceptions: null,
        },
        duels: {
          total: null,
          won: null,
        },
        dribbles: {
          attempts: null,
          success: null,
          past: null,
        },
        fouls: {
          drawn: null,
          committed: null,
        },
        cards: {
          yellow: 0,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: null,
          missed: null,
          saved: null,
        },
      },
    ],
  },
  {
    player: {
      id: 277716,
      name: 'A. Hackford',
      firstname: 'Antwoine',
      lastname: 'Hackford',
      age: 17,
      birth: {
        date: '2004-03-20',
        place: null,
        country: 'England',
      },
      nationality: 'England',
      height: null,
      weight: null,
      injured: false,
      photo: 'https://media-3.api-sports.io/football/players/277716.png',
    },
    statistics: [
      {
        team: {
          id: 62,
          name: 'Sheffield Utd',
          logo: 'https://media-1.api-sports.io/football/teams/62.png',
        },
        league: {
          id: 39,
          name: 'Premier League',
          country: 'England',
          logo: 'https://media-1.api-sports.io/football/leagues/39.png',
          flag: 'https://media-1.api-sports.io/flags/gb.svg',
          season: 2020,
        },
        games: {
          appearences: 1,
          lineups: 0,
          minutes: 10,
          number: null,
          position: 'Attacker',
          rating: '6.700000',
          captain: false,
        },
        substitutes: {
          in: 1,
          out: 0,
          bench: 1,
        },
        shots: {
          total: null,
          on: null,
        },
        goals: {
          total: 0,
          conceded: 0,
          assists: null,
          saves: null,
        },
        passes: {
          total: 1,
          key: null,
          accuracy: 1,
        },
        tackles: {
          total: null,
          blocks: null,
          interceptions: null,
        },
        duels: {
          total: 1,
          won: null,
        },
        dribbles: {
          attempts: null,
          success: null,
          past: null,
        },
        fouls: {
          drawn: null,
          committed: null,
        },
        cards: {
          yellow: 0,
          yellowred: 0,
          red: 0,
        },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
    ],
  },
];
